# Generated by Django 4.2.7 on 2023-11-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitscanapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='title',
        ),
    ]
