# Generated by Django 4.2.7 on 2023-12-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitscanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('image_data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='TestImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('image_data', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='modelweights',
            name='confusion_matrix',
            field=models.ImageField(default=1, upload_to='Performance/ConfusionMatrix/'),
            preserve_default=False,
        ),
    ]
