# Generated by Django 4.2.7 on 2023-11-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitscanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelweights',
            name='confusion_matrix',
            field=models.ImageField(upload_to='Performance/ConfusionMatrix/'),
        ),
    ]
