# Generated by Django 4.2.7 on 2023-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitscanapp', '0002_imagedata_testimagedata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelweights',
            name='test_set_accuracy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
