# Generated by Django 4.2.7 on 2023-12-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitscanapp', '0003_modelweights_test_set_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelweights',
            name='train_accuracy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='modelweights',
            name='val_accuracy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
