# Generated by Django 4.2.7 on 2023-12-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitscanapp', '0002_remove_uploadedimage_title'),
        ('fruitscanapp', '0003_imagedata'),
    ]

    operations = [
    ]
