# Generated by Django 4.2.7 on 2023-12-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitscanapp', '0004_merge_0002_remove_uploadedimage_title_0003_imagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('image_data', models.BinaryField()),
            ],
        ),
    ]
